pipeline {
    agent { node { label 'AGENT-1' } }

    stages {
        stage('Init') {
            steps {
                sh '''
                    terraform plan
                '''
            }
        }
        stage('Deploy to Staging') {  // Renamed this stage to avoid duplication
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy to Production') {  // Renamed this stage to avoid duplication
            steps {
                sh '''
                    terraform apply
                '''
            }
        }
    }
    
    post {
        always { 
            echo 'I will always run whether the job is run or not'
        }
        success {
            echo 'I will run only when the job is successful'
        }
        failure {
            echo 'I will run when there is a failure'
        }
    }
}
