pipeline {
    agent { node { label 'AGENT-1' } }

    stages {
        stage('Init') {
            steps {
             sh'''
                 cd 01-vpc
                 ls -ltr
                 pwd
                 terraform init
             '''
            }
        }
        stage('Plan') {
            steps {
                sh'''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform plan
                '''
            }
        }
        
    }
        post { 
        always { 
            echo 'I will always run weather the job is run or not'
        }
        success{
            echo ' i will run only when job is success'
        }
        failure{
            echo 'i will run when failure'
        }
    }

}
